"""Backwards-compatible barrel for the reports package.

All report queries now live in :mod:`qualcoder_api.services.reports`
(one module per report family). This module re-exports every public name so
existing imports — ``from qualcoder_api.services import report_service`` and
``from qualcoder_api.services.report_service import _STOPWORDS`` — keep
working unchanged.
"""

from qualcoder_api.services.reports import (
    _STOPWORDS,
    CODING_TABLES,
    _attr_definition,
    _attr_scope,
    _crosstab_stats,
    _krippendorff_alpha,
    _pair_report,
    _pairwise_summary,
    _sorted_values,
    _unit_coding_counts,
    _unit_coding_sets,
    _units_with_values,
    attributes_report,
    charts_data,
    code_by_variable,
    code_frequencies,
    code_relations,
    code_segments,
    code_summary,
    codebook_plain,
    coder_comparison,
    coder_file_comparison,
    codes_by_segments,
    comparison_table,
    cooccurrence,
    crosstab,
    exact_matches,
    file_summary,
    group_compare,
    interrater,
    summary_table,
    word_frequencies,
)

__all__ = [
    "CODING_TABLES",
    "_STOPWORDS",
    "_attr_definition",
    "_attr_scope",
    "_crosstab_stats",
    "_krippendorff_alpha",
    "_pair_report",
    "_pairwise_summary",
    "_sorted_values",
    "_unit_coding_counts",
    "_unit_coding_sets",
    "_units_with_values",
    "attributes_report",
    "charts_data",
    "code_by_variable",
    "code_frequencies",
    "code_relations",
    "code_segments",
    "code_summary",
    "codebook_plain",
    "coder_comparison",
    "coder_file_comparison",
    "codes_by_segments",
    "comparison_table",
    "cooccurrence",
    "crosstab",
    "exact_matches",
    "file_summary",
    "group_compare",
    "interrater",
    "summary_table",
    "word_frequencies",
]
