//! Build script — embeds the packaged backend executable into the binary.
//!
//! Runs the standard `tauri_build::build()` first (embeds the Windows
//! manifest, icon and config resources — REQUIRED for comctl32 v6 SxS
//! activation, otherwise the exe fails at load with "TaskDialogIndirect
//! entry point not found").
//!
//! If `backend/dist/qualcoder-backend.exe` exists (produced by
//! `../compile.ps1` or the PyInstaller spec), its bytes are embedded into
//! the Tauri binary so the release executable is fully self-contained:
//! the app extracts the backend to a temp file at startup and spawns it.
//! When the backend exe is absent (dev builds), the embedded slice is empty
//! and the app falls back to the venv / resource paths.

use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    tauri_build::build();

    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=tauri.conf.json");

    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let backend_exe = manifest_dir.join("../../backend/dist/qualcoder-backend.exe");
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    let out_file = out_dir.join("backend_embedded.rs");

    println!("cargo:rerun-if-changed={}", backend_exe.display());

    if backend_exe.exists() {
        // include_bytes! needs a compile-time literal path; emit one with
        // forward slashes (Windows accepts them in include_bytes).
        let lit = backend_exe.to_string_lossy().replace('\\', "/");
        fs::write(
            &out_file,
            format!(
                "// generated by build.rs — do not edit\n\
                 pub const BACKEND_EXE: &[u8] = include_bytes!(r#\"{lit}\"#);\n"
            ),
        )
        .expect("write backend_embedded.rs");
        println!("cargo:warning=embedding backend exe from {lit}");
    } else {
        fs::write(
            &out_file,
            "// generated by build.rs — backend exe not found; embedded slice is empty\n\
             pub const BACKEND_EXE: &[u8] = &[];\n",
        )
        .expect("write backend_embedded.rs");
        println!("cargo:warning=backend exe not found — release builds will use fallback discovery");
    }
}
